server:
  port: 9005

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userserrvice
    username: root
    password: User@1
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialet:org.hibernate.dialect.MySQL8Dialect


